### ISSUE TITLE
remove side effects of tests

### ISSUE THREAD

**Issue by aaronpeikert** [cjvanlissa/worcs#37]
there are some side effects of the test
1. my git name is changed constantly :facepalm: I admit its funny, but we should probably stop that.
2. many files get created under the `test/testhat/` dir
3. the output of rmarkdown render obfuscates the check/test output

**Comment by cjvanlissa** [comment]
Your git name is changed?

**Comment by aaronpeikert** [comment]
Not only mine it seems (but also andreas and maybe even yours) are changed to `yourname`
![image](https://user-images.githubusercontent.com/29424409/81544249-8cbfe900-9377-11ea-830a-ee54b982c26d.png)
It is either code in the examples or in the tests...
Because I changed it already 4 times back...
https://github.com/cjvanlissa/worcs/blob/0ffe84374adba3fb2558311a210565d3f72bf6f8/tests/testthat/test-export_project.R#L18-L19

**Comment by cjvanlissa** [comment]
1. gert can retrieve a record of the user's git signature. I think we can set and re-set that before and after the test
2. That's a bug. They should go to tempdir
3. That's probably difficult to change; rmarkdown does that. If sink() doesn't work, I wouldn't know a solution

**Comment by cjvanlissa** [comment]
1. and 3. are fixed.

For 1., I've created `worcs:::get_credentials()`, which can be used with `git_credentials()` to set either the user credentials or default credentials in tests. This way, the tests pass both locally and remotely, and they don't replace the git signature.
For 3., the function `testthat::capture_output()` is used.

**Comment by aaronpeikert** [comment]
Wow. Great, shall I tackle 2.?

**Comment by cjvanlissa** [comment]
Yes, if you can? Because I cannot reproduce the problem

**Comment by cjvanlissa** [comment]
@aaronpeikert can you confirm that all tests are now clean?

**Comment by aaronpeikert** [comment]
![image](https://user-images.githubusercontent.com/29424409/94148110-7c1b9580-fe76-11ea-9e60-5eced5781aca.png)
I still get a bunch of files in the test dir, while I would want to fix that someday, it is irrelevant for the new release.

**Comment by aaronpeikert** [comment]
But my git setup remained unchanged.
